
services:
  jupyter:
    build:
      context: .
      dockerfile: dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      my_network:
        ipv4_address: 192.168.100.2
        aliases:
          - jupyter
  postgres:
    build:
      context: .
      dockerfile: dockerfile.postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1g  # Limit memory to 1GB
        reservations:
          memory: 512m  # Reserve 512MB of memory
    networks:
      my_network:
        ipv4_address: 192.168.100.3
        aliases:
          - postgres
  mysql:
    build:
      context: .
      dockerfile: dockerfile.mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1g  # Limit memory to 1GB
        reservations:
          memory: 512m  # Reserve 512MB of memory
    networks:
      my_network:
        ipv4_address: 192.168.100.4
        aliases:
          - mysql
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 48g
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    runtime: nvidia
    networks:
      my_network:
        ipv4_address: 192.168.100.5
        aliases:
          - ollama
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1